// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           49
// Async Callback:                       1
// Total number of exported functions:  51

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    game_sc
    (
        addRaffle
        copyOperatingVector
        setQuests
        loadRarityClasses
        setCollectionIds
        issueTicketsCollection
        createTicketsToken
        issueEnergyToken
        issueHerbsToken
        issueGemsToken
        issueEssenceToken
        airdropEnergy
        clearOngoingQuests
        drawRaffleWinners
        clearRaffle
        clearTicketsHistory
        setTrialTimestamp
        setGamePaused
        stake
        unstake
        claimStakingRewards
        startQuest
        completeQuest
        joinRaffle
        getSubmittedTickets
        getParticipantsCount
        getParticipants
        getRaffles
        getTicketStats
        getStakedAddressesCount
        getStakedNFTsCount
        getStakingInfo
        getUserTokenNonces
        getRarityClasses
        getRarityClass
        getTravelersCollectionId
        getEldersCollectionId
        getTicketsId
        getEnergyTokenId
        getHerbsTokenId
        getGemsTokenId
        getEssenceTokenId
        getQuests
        getOngoingQuests
        getRaffleIndex
        getRaffleHashes
        getTxHashes
        isGamePaused
        getTrialTimestamp
        callBack
    )
}
