// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           18
// Async Callback:                       1
// Total number of exported functions:  20

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    game_sc
    (
        setTokenId
        issueEnergyToken
        issueHerbsToken
        stake
        unstake
        claimStakingRewards
        startQuest
        completeQuest
        exchange
        faucet
        receive
        getStakingRewards
        getStakedNonces
        getLastStakingTimestamp
        getTokenId
        getEnergyTokenId
        getHerbsTokenId
        getOngoingQuests
        callBack
    )
}
