// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           52
// Async Callback:                       1
// Total number of exported functions:  54

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    game_sc
    (
        setQuests
        setCollectionIds
        issueTicketsCollection
        createTicketsToken
        issueEnergyToken
        issueHerbsToken
        issueGemsToken
        issueEssenceToken
        faucet
        drawRaffleWinners
        setRaffleTimestamp
        setRafflePot
        clearRaffle
        clearTicketsHistory
        setGamePaused
        setSwappingPaused
        stake
        unstake
        claimStakingRewards
        startQuest
        completeQuest
        joinRaffle
        swapEnergy
        getSubmittedTickets
        getSubmittedTicketsTotal
        getParticipantsCount
        getParticipants
        getTicketStats
        getStakedAddressesCount
        getStakedNFTsCount
        getStakingInfo
        getLastStakingTimestamp
        getStakedAddresses
        getTravelersCollectionId
        getEldersCollectionId
        getTicketsId
        getEnergyTokenId
        getHerbsTokenId
        getGemsTokenId
        getEssenceTokenId
        getQuests
        getOngoingQuests
        getParticipantId
        getParticipantAddress
        getRaffleIndex
        getRaffleVector
        getRaffleParticipants
        getRaffleTimestamp
        getRafflePot
        getTxHashes
        isGamePaused
        isSwappingPaused
        callBack
    )
}
