#!/bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "master" ]; then
    cp env.production.json env.json
elif [ "$current_branch" = "development" ]; then
    cp env.development.json env.json
fi
